# Generated by Django 3.0.3 on 2020-03-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('publish_date', models.CharField(max_length=20)),
                ('content', models.CharField(default='No Content', max_length=200)),
            ],
        ),
    ]
