# Generated by Django 3.0.3 on 2020-03-28 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200325_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 15, 36, 1, 40181)),
        ),
    ]
