# Generated by Django 3.0.3 on 2020-03-28 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200328_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 15, 38, 23, 174649)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 15, 38, 23, 174649)),
        ),
    ]
