# Generated by Django 3.0.3 on 2020-03-28 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200328_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 16, 14, 46, 757907)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 16, 14, 46, 757907)),
        ),
    ]
